In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import numpy as np
import pandas as pd 


In [3]:
dataset = pd.read_csv('E:\AI-ML PYTHON\Restaurant_Reviews - Dr. Darshan Ingle.tsv',delimiter="\t", quoting=3)

                             # delimeter is to split the at the mean of symbol i.e.. \t is at space  like tab in words
dataset            # quoting ensures to control the quotes where to add or remove, 0 - QUOTE_MINIMAL, 1-QUOTE_ALL,
                                                                         #  2- QUOTE_NONE, 3 - QUOTE_NONNUMERIC       

Review  Liked
0                             Wow... Loved this place.      1
1                                   Crust is not good.      0
2            Not tasty and the texture was just nasty.      0
3    Stopped by during the late May bank holiday of...      1
4    The selection on the menu was great and so wer...      1
..                                                 ...    ...
995  I think food should have flavor and texture an...      0
996                           Appetite instantly gone.      0
997  Overall I was not impressed and would not go b...      0
998  The whole experience was underwhelming, and I ...      0
999  Then, as if I hadn't wasted enough of my life ...      0

[1000 rows x 2 columns]

In [4]:
dataset['Liked'].value_counts()

1    500
0    500
Name: Liked, dtype: int64

In [5]:
dataset.groupby('Liked').size()

Liked
0    500
1    500
dtype: int64

In [6]:
dataset.isnull().sum()

Review    0
Liked     0
dtype: int64

In [7]:
print(dataset['Review'])

0                               Wow... Loved this place.
1                                     Crust is not good.
2              Not tasty and the texture was just nasty.
3      Stopped by during the late May bank holiday of...
4      The selection on the menu was great and so wer...
                             ...                        
995    I think food should have flavor and texture an...
996                             Appetite instantly gone.
997    Overall I was not impressed and would not go b...
998    The whole experience was underwhelming, and I ...
999    Then, as if I hadn't wasted enough of my life ...
Name: Review, Length: 1000, dtype: object


In [8]:
print(dataset['Review'][0])

Wow... Loved this place.


In [9]:
import re
review = re.sub('[^a-zA-z]', ' ', dataset['Review'][0])
print(review)

Wow    Loved this place 


In [10]:
review = review.lower()
print(review)

wow    loved this place 


In [11]:
review = review.split()
print(review)


['wow', 'loved', 'this', 'place']


In [12]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\M
[nltk_data]     Sharath\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [13]:
from nltk.corpus import stopwords
stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

In [14]:
stopwords.words('german')

['aber',
 'alle',
 'allem',
 'allen',
 'aller',
 'alles',
 'als',
 'also',
 'am',
 'an',
 'ander',
 'andere',
 'anderem',
 'anderen',
 'anderer',
 'anderes',
 'anderm',
 'andern',
 'anderr',
 'anders',
 'auch',
 'auf',
 'aus',
 'bei',
 'bin',
 'bis',
 'bist',
 'da',
 'damit',
 'dann',
 'der',
 'den',
 'des',
 'dem',
 'die',
 'das',
 'dass',
 'daß',
 'derselbe',
 'derselben',
 'denselben',
 'desselben',
 'demselben',
 'dieselbe',
 'dieselben',
 'dasselbe',
 'dazu',
 'dein',
 'deine',
 'deinem',
 'deinen',
 'deiner',
 'deines',
 'denn',
 'derer',
 'dessen',
 'dich',
 'dir',
 'du',
 'dies',
 'diese',
 'diesem',
 'diesen',
 'dieser',
 'dieses',
 'doch',
 'dort',
 'durch',
 'ein',
 'eine',
 'einem',
 'einen',
 'einer',
 'eines',
 'einig',
 'einige',
 'einigem',
 'einigen',
 'einiger',
 'einiges',
 'einmal',
 'er',
 'ihn',
 'ihm',
 'es',
 'etwas',
 'euer',
 'eure',
 'eurem',
 'euren',
 'eurer',
 'eures',
 'für',
 'gegen',
 'gewesen',
 'hab',
 'habe',
 'haben',
 'hat',
 'hatte',
 'hatten',
 '

In [15]:
review = [w for w in review if not w in set(stopwords.words('english'))]
print(review)

['wow', 'loved', 'place']


In [17]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()
review = [ps.stem(w) for w in review]
print(review)

['wow', 'love', 'place']


In [18]:
review = ' '.join(review)
print(review)

wow love place


In [79]:
corpus1 = []
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features=3)
print(review)
corpus1.append(review)
print(corpus1)


wow love place
['wow love place']


In [80]:
X = cv.fit_transform(corpus1)


In [81]:
X.toarray()

array([[1, 1, 1]], dtype=int64)

In [82]:
dataset.shape

(1000, 2)

In [21]:
import re
from nltk.stem.porter import PorterStemmer
from sklearn.feature_extraction.text import CountVectorizer
from nltk.corpus import stopwords
corpus = []

for i in range(0,1000):
    review = re.sub('[^a-zA-Z]',' ',dataset['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(w) for w in review if not w in set(stopwords.words('english'))]

    review = ' '.join(review)
    print(review)
    corpus.append(review)

wow love place
crust good
tasti textur nasti
stop late may bank holiday rick steve recommend love
select menu great price
get angri want damn pho
honeslti tast fresh
potato like rubber could tell made ahead time kept warmer
fri great
great touch
servic prompt
would go back
cashier care ever say still end wayyy overpr
tri cape cod ravoli chicken cranberri mmmm
disgust pretti sure human hair
shock sign indic cash
highli recommend
waitress littl slow servic
place worth time let alon vega
like
burritto blah
food amaz
servic also cute
could care less interior beauti
perform
right red velvet cake ohhh stuff good
never brought salad ask
hole wall great mexican street taco friendli staff
took hour get food tabl restaur food luke warm sever run around like total overwhelm
worst salmon sashimi
also combo like burger fri beer decent deal
like final blow
found place accid could happier
seem like good quick place grab bite familiar pub food favor look elsewher
overal like place lot
redeem qualiti r

In [22]:
print(corpus)

['wow love place', 'crust good', 'tasti textur nasti', 'stop late may bank holiday rick steve recommend love', 'select menu great price', 'get angri want damn pho', 'honeslti tast fresh', 'potato like rubber could tell made ahead time kept warmer', 'fri great', 'great touch', 'servic prompt', 'would go back', 'cashier care ever say still end wayyy overpr', 'tri cape cod ravoli chicken cranberri mmmm', 'disgust pretti sure human hair', 'shock sign indic cash', 'highli recommend', 'waitress littl slow servic', 'place worth time let alon vega', 'like', 'burritto blah', 'food amaz', 'servic also cute', 'could care less interior beauti', 'perform', 'right red velvet cake ohhh stuff good', 'never brought salad ask', 'hole wall great mexican street taco friendli staff', 'took hour get food tabl restaur food luke warm sever run around like total overwhelm', 'worst salmon sashimi', 'also combo like burger fri beer decent deal', 'like final blow', 'found place accid could happier', 'seem like go

In [85]:
corpus_dataset = pd.DataFrame(corpus)
print(corpus_dataset)

                                                     0
0                                       wow love place
1                                           crust good
2                                   tasti textur nasti
3    stop late may bank holiday rick steve recommen...
4                              select menu great price
..                                                 ...
995                      think food flavor textur lack
996                             appetit instantli gone
997                       overal impress would go back
998  whole experi underwhelm think go ninja sushi n...
999  wast enough life pour salt wound draw time too...

[1000 rows x 1 columns]


In [86]:
corpus_dataset.columns = ['columns']
corpus_dataset.head()

columns
0                                     wow love place
1                                         crust good
2                                 tasti textur nasti
3  stop late may bank holiday rick steve recommen...
4                            select menu great price

In [87]:
corpus_dataset.columns

Index(['columns'], dtype='object')

In [88]:
corpus_dataset.shape

(1000, 1)

In [89]:
corpus_dataset.to_csv('corpus_dataset')

In [90]:
import os 
os.getcwd()

'C:\\Users\\M Sharath\\AI-ML\\ML PYTHON 2'

In [94]:
cv = CountVectorizer(max_features=1500)
X = cv.fit_transform(corpus).toarray()



In [95]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [97]:
print(cv.get_feature_names())

['absolut', 'absolutley', 'accid', 'accommod', 'accomod', 'accordingli', 'account', 'ach', 'acknowledg', 'across', 'actual', 'ad', 'afford', 'afternoon', 'ago', 'ahead', 'airlin', 'airport', 'ala', 'albondiga', 'allergi', 'almond', 'almost', 'alon', 'also', 'although', 'alway', 'amaz', 'ambianc', 'ambienc', 'amount', 'ampl', 'andddd', 'angri', 'annoy', 'anoth', 'anticip', 'anymor', 'anyon', 'anyth', 'anytim', 'anyway', 'apart', 'apolog', 'app', 'appal', 'appar', 'appeal', 'appet', 'appetit', 'appl', 'approv', 'area', 'arepa', 'aria', 'around', 'array', 'arriv', 'articl', 'ask', 'assur', 'ate', 'atmospher', 'atroci', 'attach', 'attack', 'attent', 'attitud', 'auju', 'authent', 'averag', 'avocado', 'avoid', 'aw', 'away', 'awesom', 'awkward', 'awkwardli', 'ayc', 'az', 'baba', 'babi', 'bachi', 'back', 'bacon', 'bad', 'bagel', 'bakeri', 'baklava', 'ball', 'bamboo', 'banana', 'bank', 'bar', 'bare', 'bargain', 'bartend', 'base', 'basebal', 'basic', 'batch', 'bathroom', 'batter', 'bay', 'bbq', 

In [98]:
len(cv.get_feature_names())

1500

In [100]:
y = dataset.iloc[:,1].values

In [101]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 10, test_size = 0.3)


In [105]:
from sklearn.naive_bayes import GaussianNB
gb = GaussianNB()
classifier = gb.fit(X_train,y_train)
y_pred = classifier.predict(X_test)


In [106]:
from sklearn.metrics import confusion_matrix,classification_report,accuracy_score

accuracy = accuracy_score(y_test,y_pred)
print(accuracy)
cm = confusion_matrix(y_test,y_pred)
print(cm)
report = classification_report(y_test,y_pred)
print(report)

0.6466666666666666
[[ 86  72]
 [ 34 108]]
              precision    recall  f1-score   support

           0       0.72      0.54      0.62       158
           1       0.60      0.76      0.67       142

    accuracy                           0.65       300
   macro avg       0.66      0.65      0.64       300
weighted avg       0.66      0.65      0.64       300



In [110]:
review = 'very long queue and waiting'
input_data = [review]
input = cv.transform(input_data).toarray()
y_predict = classifier.predict(input)

if y_predict == 1:
    print('review is positive')
else:
    print('review is negative')

review is negative


In [111]:
review = 'excellent  and delicious food'
input_data = [review]
input = cv.transform(input_data).toarray()
y_predict = classifier.predict(input)

if y_predict == 1:
    print('review is positive')
else:
    print('review is negative')

review is positive


In [112]:
from sklearn.ensemble import RandomForestClassifier
RFC = RandomForestClassifier(n_estimators=98,criterion='entropy',random_state=0)
RFC.fit(X_train,y_train)
ypred = RFC.predict(X_test)

In [114]:
print(classification_report(y_test,ypred))


              precision    recall  f1-score   support

           0       0.75      0.85      0.80       158
           1       0.80      0.69      0.74       142

    accuracy                           0.77       300
   macro avg       0.78      0.77      0.77       300
weighted avg       0.78      0.77      0.77       300



In [117]:
inputs = ['not delicios and worst service']
input = cv.transform(inputs).toarray()
inputpredict = RFC.predict(input)
if inputpredict == 1:
    print('Review is positive')
else:
    print('Review is negative')

Review is negative
