In [1]:
import warnings
warnings.simplefilter('ignore')

In [2]:
import  numpy as np 
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt
import pickle # which is used to save the model

In [3]:
df = pd.read_csv('E:\AI-ML PYTHON\hiring.csv')
df.head()

experience  test_score  interview_score  salary
0        NaN         8.0                9   50000
1        NaN         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [4]:
df.shape

(8, 4)

In [5]:
df.isna().sum()

experience         2
test_score         1
interview_score    0
salary             0
dtype: int64

In [6]:
df['experience'].fillna(0, inplace=True)

In [7]:
df.isna().sum()

experience         0
test_score         1
interview_score    0
salary             0
dtype: int64

In [8]:
df['test_score'].mean()

7.857142857142857

In [9]:
df['test_score'].fillna(df['test_score'].mean(),inplace=True)

In [10]:
df.isna().sum()

experience         0
test_score         0
interview_score    0
salary             0
dtype: int64

In [11]:
df.head()

experience  test_score  interview_score  salary
0          0         8.0                9   50000
1          0         8.0                6   45000
2       five         6.0                7   60000
3        two        10.0               10   65000
4      seven         9.0                6   70000

In [12]:
X = df.iloc[:,:-1]
X.head()

experience  test_score  interview_score
0          0         8.0                9
1          0         8.0                6
2       five         6.0                7
3        two        10.0               10
4      seven         9.0                6

In [13]:
X.shape

(8, 3)

In [14]:
# converting text to nos

def conv(x):
    dict = { 'two':2, 'three':3, 'five':5, 'seven':7, 'ten':10, 0:0, 'eleven':11}
    return dict[x]

In [15]:
X['experience'] = X['experience'].apply(lambda x: conv(x))

In [16]:
X.head()

experience  test_score  interview_score
0           0         8.0                9
1           0         8.0                6
2           5         6.0                7
3           2        10.0               10
4           7         9.0                6

In [17]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8 entries, 0 to 7
Data columns (total 3 columns):
 #   Column           Non-Null Count  Dtype  
---  ------           --------------  -----  
 0   experience       8 non-null      int64  
 1   test_score       8 non-null      float64
 2   interview_score  8 non-null      int64  
dtypes: float64(1), int64(2)
memory usage: 320.0 bytes


### X is ready now 

In [18]:
y = df.iloc[:,-1]

In [19]:
y 

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [20]:
y.shape

(8,)

 - This dataset is very small so not recommended to do traintestsplit over here.it can be performed with other datasets as we know.
 
 - The main agenda is deployment part 


In [21]:
# modelling 
from sklearn.linear_model import LinearRegression
lr = LinearRegression()


In [22]:
lr.fit(X,y)

LinearRegression()

In [23]:
y_pred = lr.predict(X)

In [24]:
y_pred

array([52313.61238494, 45722.68644263, 58231.95591138, 63991.7318464 ,
       67429.06277517, 61080.55179794, 75922.72532666, 79307.67351488])

In [25]:
y

0    50000
1    45000
2    60000
3    65000
4    70000
5    62000
6    72000
7    80000
Name: salary, dtype: int64

In [26]:
from sklearn.metrics import r2_score
r2_score = r2_score(y_pred, y)

In [27]:
r2_score

0.9626511210293307

In [28]:
X

experience  test_score  interview_score
0           0    8.000000                9
1           0    8.000000                6
2           5    6.000000                7
3           2   10.000000               10
4           7    9.000000                6
5           3    7.000000               10
6          10    7.857143                7
7          11    7.000000                8

In [29]:
lr.predict([[4,5,8]])

array([55688.35915181])

In [30]:
lr.predict([[0,0,0]])

array([17237.33031373])

In [31]:
lr.predict([[10,10,10]])

array([86612.80419155])

# Model Deployment

In [32]:
import pickle
pickle.dump(lr, open('model.pkl','wb'))

# Dump this model called 'lr' by the name 'model.pkl' in our systems HDD 
# while doing this write the file using 'write bytes' mode.

In [33]:
# Load the model and read ---if it is client side operation
client_model = pickle.load(open('model.pkl', 'rb'))

In [34]:
client_model.predict([[7,7,5]])

array([61406.21139999])

In [35]:
client_model.predict([[3,6,5]])

array([48182.73719688])